/**
 * Rise of Ix regression manifest — paraphrased from `.cursor/rise_of_ix` and the RoI rulebook.
 * Used by `riseOfIxImperium.test.ts` for coverage stubs and corner-case notes.
 */
export interface RiseOfIxImperiumEntry {
  name: string
  qty: number
  cost: number
  agentBox: string
  reveal: string
  unload?: boolean
  /** Corner cases / integration notes for implementers. */
  cornerCases?: string[]
}

export const riseOfIxImperiumManifest: RiseOfIxImperiumEntry[] = [
  {
    name: 'Appropriate',
    qty: 1,
    cost: 5,
    agentBox: '2× Inf EM → +1 Tech (may pay Solari instead of spice)',
    reveal: '2 persuasion',
    cornerCases: ['EM influence gate', 'acquireTech paySolariInsteadOfSpice', 'unload +1 freighter on discard'],
  },
  {
    name: 'Bounty Hunter',
    qty: 1,
    cost: 1,
    agentBox: '+2 Solari when infiltrating occupied space',
    reveal: '1 persuasion, 1 sword',
    cornerCases: ['infiltrate flag', 'no bonus on empty space', 'no bonus without infiltrate path'],
  },
  {
    name: 'CHOAM Delegate',
    qty: 1,
    cost: 1,
    agentBox: '(none)',
    reveal: '+3 Solari',
    unload: true,
    cornerCases: ['unload freighter choice on discard/trash only'],
  },
  {
    name: 'Court Intrigue',
    qty: 1,
    cost: 2,
    agentBox: '−1 intrigue (bottom) → +1 intrigue',
    reveal: '1 persuasion, 1 sword',
    cornerCases: ['intrigueBottom cost requires intrigue in hand'],
  },
  {
    name: 'Desert Ambush',
    qty: 1,
    cost: 3,
    agentBox: '(none)',
    reveal: '1 persuasion, 1 sword; 1 enemy retreat per troop deployed this turn',
    cornerCases: ['retreat allowance scales with troopsDeployedToConflict', '0 deploy → no retreat'],
  },
  {
    name: 'Embedded Agent',
    qty: 1,
    cost: 5,
    agentBox: 'Another BG in play → +2 shipping',
    reveal: '1 persuasion, 1 intrigue',
    cornerCases: ['inPlay BG requirement', 'freighter:2 not freighter choice'],
  },
  {
    name: 'Esmar Tuek',
    qty: 1,
    cost: 5,
    agentBox: '−1 spice → +1 SG influence, draw 1',
    reveal: '+2 spice, +2 Solari',
    unload: true,
    cornerCases: ['optional spice cost', 'unload on discard'],
  },
  {
    name: 'Freighter Fleet',
    qty: 2,
    cost: 2,
    agentBox: '(none)',
    reveal: '+1 shipping',
    unload: true,
  },
  {
    name: 'Full-Scale Assault',
    qty: 1,
    cost: 8,
    agentBox: '+2 troops',
    reveal: '2 persuasion; +3 combat per dreadnought in conflict',
    cornerCases: ['acquire dreadnought', '0 dreadnoughts → no sword bonus', 'needs unit in conflict'],
  },
  {
    name: 'Guild Accord',
    qty: 1,
    cost: 6,
    agentBox: 'Heighliner −2 spice this turn',
    reveal: '+1 water; SG alliance → +3 spice',
    unload: true,
    cornerCases: ['heighlinerDiscountThisTurn', 'alliance requirement on reveal'],
  },
  {
    name: 'Guild Chief Administrator',
    qty: 1,
    cost: 4,
    agentBox: 'discard 1 → trash 1',
    reveal: '1 persuasion, +1 shipping',
    cornerCases: ['discard then trash choice order'],
  },
  {
    name: 'Imperial Bashar',
    qty: 1,
    cost: 4,
    agentBox: '+1 troop OR trash 1',
    reveal: '1 persuasion; +2 combat +1 per other revealed sword card',
    cornerCases: ['OR agent choice', 'bashar swords need troops in conflict'],
  },
  {
    name: 'Imperial Shock Trooper',
    qty: 1,
    cost: 3,
    agentBox: '(no agent icons — reveal only)',
    reveal: '1 persuasion; +2 combat or +5 if agent on Emperor space',
    cornerCases: ['no agent turn', 'EM space detection includes faction Emperor spaces'],
  },
  {
    name: 'In the Shadows',
    qty: 2,
    cost: 2,
    agentBox: '2× Inf BG: discard 1 → +1 inf (EM/SG/FR)',
    reveal: '+1 BG influence',
    unload: true,
    cornerCases: ['BG influence gate', 'NON_BG influence choose-one'],
  },
  {
    name: 'Ix-Guild Compact',
    qty: 1,
    cost: 3,
    agentBox: 'discard 2 → +1 dreadnought',
    reveal: '+2 negotiators',
    unload: true,
    cornerCases: ['commission cap 2 active dreadnoughts'],
  },
  {
    name: 'Ixian Engineer',
    qty: 2,
    cost: 5,
    agentBox: '+1 Tech',
    reveal: '3+ tech owned → may trash this for +1 VP',
    cornerCases: ['acquireTech pending', 'optional trash-for-VP at 3 tech'],
  },
  {
    name: 'Jamis',
    qty: 1,
    cost: 2,
    agentBox: 'trash 1',
    reveal: '1 persuasion, 2 swords',
    cornerCases: ['infiltrate'],
  },
  {
    name: 'Landing Rights',
    qty: 1,
    cost: 4,
    agentBox: '+1 shipping',
    reveal: '2 persuasion',
  },
  {
    name: 'Local Fence',
    qty: 1,
    cost: 3,
    agentBox: '−2 spice → +5 Solari OR −5 Solari → +4 spice',
    reveal: '2 persuasion',
    cornerCases: ['mutually exclusive OR costs'],
  },
  {
    name: 'Negotiated Withdrawel',
    qty: 2,
    cost: 4,
    agentBox: '(none)',
    reveal: '2 persuasion; retreat 3 troops → +1 influence (choose)',
    cornerCases: ['acquire +1 troop', 'retreat allowance +3', 'influence choose-one'],
  },
  {
    name: 'Satellite Ban',
    qty: 1,
    cost: 5,
    agentBox: 'discard 1 → +1 spice, +1 water',
    reveal: '1 persuasion; retreat up to 2 troops',
    cornerCases: ['dual faction icons SG+FR'],
  },
  {
    name: 'Sayyadina',
    qty: 1,
    cost: 3,
    agentBox: '−3 water → +1 VP',
    reveal: 'FR bond → 3 persuasion',
    cornerCases: ['water cost', 'bond requirement'],
  },
  {
    name: 'Shai-Hulud',
    qty: 1,
    cost: 7,
    agentBox: 'trash 1 → +2 troops',
    reveal: 'FR bond → +5 combat',
    cornerCases: ['acquire trash 1', 'bond gate on reveal swords'],
  },
  {
    name: 'Spice Trader',
    qty: 1,
    cost: 4,
    agentBox: '2× Inf FR: discard 1 → +2 spice',
    reveal: '2 persuasion, 1 sword',
    cornerCases: ['FR influence gate'],
  },
  {
    name: 'Treachery',
    qty: 2,
    cost: 6,
    agentBox: '2 influence per faction icon; trash this card',
    reveal: '+2 troops, deploy 2 to conflict',
    unload: true,
    cornerCases: ['4 faction icons → up to 8 influence', 'unload deploy on discard/trash'],
  },
  {
    name: 'Truthsayer',
    qty: 2,
    cost: 3,
    agentBox: 'discard 1 → draw 1',
    reveal: '1 persuasion, 1 sword',
  },
  {
    name: 'Water Peddler',
    qty: 1,
    cost: 1,
    agentBox: '(no agent icons)',
    reveal: '+1 water',
    unload: true,
    cornerCases: ['acquire +1 water', 'unload not on reveal cleanup'],
  },
  {
    name: 'Web of Power',
    qty: 1,
    cost: 4,
    agentBox: 'Per faction with 2+ inf: EM +2 Solari, SG draw, FR +1 water',
    reveal: '1 persuasion; +1 influence (choose)',
    cornerCases: ['infiltrate', 'partial faction rewards'],
  },
  {
    name: 'Weirding Way',
    qty: 1,
    cost: 3,
    agentBox: 'Take another turn after this one',
    reveal: '1 persuasion, 2 swords',
    cornerCases: ['extraTurnAllowed', 'consume on next END_TURN rotation'],
  },
]
